---

- name: Install locales package
  become: true
  ansible.builtin.apt:
    name: locales
    state: present
    update_cache: true

- name: Ensure a locale exists
  become: true
  community.general.locale_gen:
    name: "{{ base_locale }}"
    state: present

- name: Set timezone to "{{ base_timezone }}"
  become: true
  when: base_timezone is defined
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ssh config strict hostkey
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    line: 'StrictHostKeyChecking no'

- name: Ssh config userknown
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    line: 'UserKnownHostsFile /dev/null'

- name: Ensure low swappiness value
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present

...
