---

- name: Set default system language
  become: true
  when: base_locale is defined
  ansible.builtin.command: locale-gen "{{ base_locale }}"
  args:
    creates: "{{ base_firstboot_creates_path }}"

- name: Set timezone to "{{ base_timezone }}"
  become: true
  when: base_timezone is defined
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Build hosts file
  become: true
  when: hostvars[inventory_hostname]['ansible_host'] is defined
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ ansible_play_hosts }}"

- name: Ssh config strict hostkey
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    line: 'StrictHostKeyChecking no'

- name: Ssh config userknown
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    line: 'UserKnownHostsFile /dev/null'

- name: Ensure low swappiness value
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present

...
