---

- name: Get packages list
  ansible.builtin.include_vars: "packages.yml"

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
    force: true

...
