---

- name: Ensure admin group is present
  become: true
  ansible.builtin.group:
    name: admin
    state: present

- name: Ansible user properties
  become: true
  ansible.builtin.user:
    append: true
    name: "{{ ansible_user }}"
    shell: /bin/bash
    password: '*'
    groups:
      - admin

- name: No passwd for admin group on sudo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

...
