---

- name: Create cert_manager namespace
  kubernetes.core.k8s:
    name: "{{ cert_manager_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url: "{{ cert_manager_repo }}"

- name: Deploy cert_manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager/cert-manager
    chart_version: "{{ cert_manager_version }}"
    release_namespace: "{{ cert_manager_namespace }}"
    values:
      installCRDs: true
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000

- name: Create CRD cert Staging Issuer
  kubernetes.core.k8s:
    state: present
    template: issuer-staging.yml.j2

- name: Create CRD cert Prod Issuer
  kubernetes.core.k8s:
    state: present
    template: issuer-production.yml.j2

- name: Create CRD cert self-signed Issuer
  kubernetes.core.k8s:
    state: present
    template: issuer-selfsigned.yml.j2
...
