---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/sonar.yml

- name: Add sonar chart repo
  community.kubernetes.helm_repository:
    name: sonarqube
    repo_url: "https://oteemo.github.io/charts"

- name: Deploy SonarQube
  community.kubernetes.helm:
    name: sonarqube
    chart_ref: sonarqube/sonarqube
    chart_version: 9.6.0
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/sonar.yml

