---

crio_version: 1.32

crio_mirror: ""
crio_mirror_insecure: false

crio_repo_url: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:"

crio_keyring_key_path: /usr/share/keyrings/crio-keyring.gpg

...
