---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/jenkinsx.yml

- name: Add jenkins chart repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io"

- name: Deploy Jenkins
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    chart_version: 4.2.10
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/jenkinsx.yml

