---

- name: Add helm apt key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  become: yes

- name: Add helm apt repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
  become: yes

- name: Install helm package
  apt:
    name: helm
    update_cache: yes
  become: yes

- name: Add stable repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable

- name: Add incubator repository
  kubernetes.core.helm_repository:
    name: incubator
    repo_url: https://charts.helm.sh/incubator

