---

- name: Sign pending certificates
  ansible.builtin.shell: |
    set -e -o pipefail
    kubectl get csr -o name | xargs kubectl certificate approve
  args:
    executable: /bin/bash
  changed_when: false

- name: Wait for control-plane pods become created
  ansible.builtin.shell: "kubectl get po --namespace=kube-system --selector tier=control-plane --output=jsonpath='{.items[*].metadata.name}'"
  register: postinstall_control_plane_pods_created
  until: item in postinstall_control_plane_pods_created.stdout
  retries: 10
  delay: 30
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  changed_when: false

- name: Wait for control-plane pods become ready
  ansible.builtin.command: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s"
  changed_when: false

- name: Wait for kube-proxy become created
  ansible.builtin.command: "kubectl get po --namespace=kube-system --selector k8s-app=kube-proxy --output=jsonpath='{.items[*].metadata.name}'"
  register: postinstall_kube_proxy_pods_created
  until: item in postinstall_kube_proxy_pods_created.stdout
  retries: 30
  delay: 10
  with_items:
    - kube-proxy
  changed_when: false

- name: Wait for kube-proxy pods become ready
  ansible.builtin.command: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector k8s-app=kube-proxy --timeout=600s"
  changed_when: false

- name: Wait for kube-system pods become ready
  ansible.builtin.command: "kubectl wait pod --all --namespace=kube-system --for=condition=Ready --timeout=600s"
  changed_when: false

...
