---

- name: Enable ip forward
  become: yes
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Add br_netfilter module
  become: yes
  modprobe:
    name: br_netfilter
    state: present

- include_vars: "packages.yml"

- name: Prepare deb repos
  become: yes
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_os }}/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.list

    mkdir -p /usr/share/keyrings
    curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/Release.key | gpg --yes --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
    curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_os }}/Release.key | gpg --yes --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

- name: Install crio packages
  become: yes
  apt:
    name: "{{ crio_packages }}"
    state: present
    update_cache: true
    force: yes

- name: Remove crio bridge (conflict with calico)
  become: yes
  file:
    path: /etc/cni/net.d/100-crio-bridge.conflist
    state: absent

- name: Remove loopback cni (conflict with calico)
  become: yes
  file:
    path: /etc/cni/net.d/200-loopback.conflist
    state: absent

- name: Ensure containers etc folder exist
  become: yes
  when: crio_mirror != ''
  file:
    path: /etc/containers/registries.conf.d
    state: directory
    mode: 0755

- name: Registries config
  become: yes
  when: crio_mirror != ''
  template:
    src: templates/registries.conf.j2
    dest: /etc/containers/registries.conf.d/001-dockerhub-mirror.conf
    mode: 0644

- name: enable crio service
  become: yes
  service:
    name: crio
    enabled: yes
    state: started
