---

- name: Enable ip forward
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Add br_netfilter module
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Get cri-o packages list
  ansible.builtin.include_vars: "packages.yml"

- name: Ensure keyring folder is here
  become: true
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Get key
  become: true
  ansible.builtin.apt_key:
    url: "{{ crio_repo_url }}/v{{ crio_version }}/deb/Release.key"
    keyring: "{{ crio_keyring_key_path }}"

- name: Add CRI-O repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ crio_keyring_key_path }}] {{ crio_repo_url }}/v{{ crio_version }}/deb/ /"
    state: present

- name: Install crio packages
  become: true
  ansible.builtin.apt:
    name: "{{ crio_packages }}"
    state: present
    update_cache: true
    force: true

- name: Remove crio bridge (conflict with calico)
  become: true
  ansible.builtin.file:
    path: /etc/cni/net.d/100-crio-bridge.conflist
    state: absent

- name: Remove loopback cni (conflict with calico)
  become: true
  ansible.builtin.file:
    path: /etc/cni/net.d/200-loopback.conflist
    state: absent

- name: Ensure containers etc folder exist
  become: true
  when: crio_mirror != ''
  ansible.builtin.file:
    path: /etc/containers/registries.conf.d
    state: directory
    mode: '0755'

- name: Registries config
  become: true
  when: crio_mirror != ''
  ansible.builtin.template:
    src: templates/registries.conf.j2
    dest: /etc/containers/registries.conf.d/001-images-mirror.conf
    mode: '0644'

- name: Enable crio service
  become: true
  ansible.builtin.service:
    name: crio
    enabled: true
    state: started

...
