---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/keycloak.yml

- name: Add codecentric keycloak chart repo
  community.kubernetes.helm_repository:
    name: codecentric
    repo_url: "https://codecentric.github.io/helm-charts"

- name: Deploy Keycloak
  community.kubernetes.helm:
    name: keycloak
    chart_ref: codecentric/keycloak
    chart_version: 10.1.0
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/keycloak.yml

