---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/registry.yml

- name: Deploy docker registry
  community.kubernetes.helm:
    name: registry
    chart_ref: stable/docker-registry
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/registry.yml

