---

- name: import ssl certificate
  shell: |
    kubectl create secret tls {{ ingress_cert_name }} --key {{ ingress_cert_key }} --cert {{ ingress_cert_path }}
    touch ~/.ingress_cert_secret
  args:
    executable: /bin/bash
    creates: ~/.ingress_cert_secret

- name: Add nginx ingress chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Deploy Nginx Ingress
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.3.0
    release_namespace: k8s
    create_namespace: yes

- name: Ensure ingress is ready
  pause:
    seconds: 150

- name: Delete ingress admission webhook
  shell: kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
