---

- name: Create ingress namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          kubernetes.io/metadata.name: "{{ ingress_namespace }}"
          name: "{{ ingress_namespace }}"
          pod-security.kubernetes.io/enforce: baseline
        name: "{{ ingress_namespace }}"

- name: Add traefik ingress chart repo
  kubernetes.core.helm_repository:
    name: ingress-traefik
    repo_url: "https://traefik.github.io/charts"

- name: Deploy Traefik Ingress
  kubernetes.core.helm:
    name: ingress-traefik
    chart_ref: ingress-traefik/traefik
    chart_version: "{{ ingress_chart_version }}"
    release_namespace: "{{ ingress_namespace }}"
    create_namespace: true
    values:
      service:
        type: "NodePort"
        nodePorts:
          http: "{{ ingress_http_port }}"
          https: "{{ ingress_https_port }}"
      metrics:
        prometheus:
          enabled: true
      ingressClass:
        enabled: true
        isDefaultClass: true

- name: Wait for ingress become created
  ansible.builtin.command: |
    kubectl get po --namespace={{ ingress_namespace }} --selector app.kubernetes.io/name=traefik --output=jsonpath='{.items[*].metadata.name}'
  register: ingress_pods_created
  until: item in ingress_pods_created.stdout
  retries: 30
  delay: 10
  changed_when: false
  with_items:
    - traefik

- name: Wait for ingress pods become ready
  ansible.builtin.command: |
    kubectl wait --namespace={{ ingress_namespace }} --for=condition=Ready pods --selector app.kubernetes.io/name=traefik --timeout=600s
  changed_when: false

...
