---

- name: Install haproxy package
  become: true
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: Write haproxy configuration
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Start haproxy service
  become: true
  ansible.builtin.service:
    name: haproxy
    state: started

- name: Flush haproxy restart handler
  ansible.builtin.meta: flush_handlers

...
