---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/grafana.yml

- name: Add grafana chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Deploy Grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    chart_version: 6.7.2
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/grafana.yml

