---

- name: Pypi internal repository
  when: internal_repos_pypi != ""
  ansible.builtin.import_tasks: pypi.yml

- name: Apt internal repository
  when: internal_repos_apt != ""
  ansible.builtin.import_tasks: apt.yml

...
