---

- name: Define ssh_config
  become: true
  ansible.builtin.template:
    src: ssh_config
    dest: /etc/ssh/ssh_config
    mode: '0644'

- name: Define sshd_config
  become: true
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'
  notify:
    - Restart ssh

...
