---

logcollect_namespace: "logcollect"

logcollect_persistence_disk: false
logcollect_kibana_domain: "logcollect.k8s.local"
logcollect_cert_issuer: "selfsigned-ca"

logcollect_fluentbit_version: "0.37.1"
logcollect_elasticsearch_version: "8.5.1"
logcollect_kibana_version: "8.5.1"

...
