---

- name: Taint nodes for cilium purpose
  ansible.builtin.command: |
    kubectl taint nodes {{ item.name }} {{ cni_cilium_node_taints }}
  args:
    creates: "{{ ansible_env.HOME }}/.cni_install"
  loop: "{{ cni_k8s_nodes }}"

- name: Add cilium chart repo
  kubernetes.core.helm_repository:
    name: cilium-cni
    repo_url: "{{ cni_cilium_helm_repo }}"

- name: Create cilium namespace
  kubernetes.core.k8s:
    name: "{{ cni_cilium_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: "cilium-cni/cilium"
    chart_version: "{{ cni_cilium_version }}"
    release_namespace: "{{ cni_cilium_namespace }}"
    set_values:
      - value: ipv4NativeRoutingCIDR=10.244.0.0/16
        value_type: string
      - value: k8s.requireIPv4PodCIDR=true
        value_type: string

- name: Wait for cilium pods become ready
  ansible.builtin.command: "kubectl wait pod --all --namespace={{ cni_cilium_namespace }} --for=condition=Ready --timeout=1200s"
  changed_when: false

...
