---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/borgmon.yml

- name: Add prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy Prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus/prometheus
    chart_version: 13.6.0
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/borgmon.yml

