---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Add elastic chart repo
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Elasticsearch Values parameters file
  template:
    src: templates/elasticsearch.yml.j2
    dest: helm-values/elasticsearch.yml

- name: Deploy Elasticsearch
  community.kubernetes.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    chart_version: 7.12.0
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/elasticsearch.yml

- name: Kibana Values parameters file
  template:
    src: templates/kibana.yml.j2
    dest: helm-values/kibana.yml

- name: Deploy Kibana
  community.kubernetes.helm:
    name: kibana
    chart_ref: elastic/kibana
    chart_version: 7.12.0
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/kibana.yml

- name: Deploy MetricBeat
  community.kubernetes.helm:
    name: metricbeat
    chart_ref: elastic/metricbeat
    chart_version: 7.12.0
    release_namespace: k8s
    create_namespace: yes

