---
- name: Install prerequisites and kubernetes packages
  hosts:
    - managers
    - nodes
  strategy: linear
  roles:
    - role: internal_repos
    - role: base
    - role: crio
    - role: kubernetes
      become: true

- name: Install prerequisites on first manager node
  hosts:
    - leader 
  run_once: true
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cert

- name: Init kubernetes on manager nodes
  hosts:
    - managers
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: helm
    - role: keepalived
    - role: k8s

- name: Init kubernetes on worker nodes
  hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s

- name: Postinstall fine-tuning and install tools & services
  hosts:
    - leader 
  #run_once: true
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cni
    - role: csi
    - role: postinstall
    - role: ingress
    - role: cert_manager
    - role: kubedashboard
    - role: opa
    - role: monitoring
...
