---
- name: Install prerequisites and kubernetes packages
  hosts:
    - managers
    - nodes
  strategy: linear
  roles:
    - role: base
    - role: crio
    - role: kubernetes
      become: true

- name: Install prerequisites on first manager node
  hosts:
    - man01
  run_once: true
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cert
    - role: helm

- name: Init kubernetes on manager nodes
  hosts:
    - managers
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: keepalived
      when: global_cloud == 'no'
    - role: k8s
      tags: ["k8s"]

- name: Init kubernetes on worker nodes
  hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s

- name: Postinstall fine-tuning and install tools & services
  hosts:
    - man01
  run_once: true
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cni
    - role: postinstall
    - role: ingress
    - role: kubedashboard
    - role: opa

...
