---
- name: Install prerequisites and kubernetes packages
  hosts:
    - managers
    - nodes
  strategy: linear
  roles:
    - role: internal_repos
      tags: ["core"]
    - role: base
      tags: ["core"]
    - role: linux_hardening
      tags: ["core", "hardening"]
    - role: crio
      tags: ["core"]
    - role: kubernetes
      tags: ["core"]
      become: true

- name: Init kubernetes on manager nodes
  hosts:
    - managers
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: helm
      tags: ["controlplane"]
    - role: keepalived
      tags: ["controlplane"]
    - role: k8s
      tags: ["controlplane"]
    - role: haproxy
      tags: ["controlplane"]

- name: Init kubernetes on worker nodes
  hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s
      tags: ["worker"]

- name: Postinstall fine-tuning and install tools & services
  hosts:
    - leader
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cni
      tags: ["cluster", "cni"]
    - role: csi
      tags: ["cluster", "csi"]
    - role: postinstall
      tags: ["cluster", "postinstall"]
    - role: ingress
      tags: ["cluster", "ingress"]
    - role: cert_manager
      tags: ["cluster", "certs", "certmanager"]
    - role: kubedashboard
      tags: ["cluster", "dashboard"]
    - role: opa
      tags: ["cluster", "opa"]
    - role: monitoring
      tags: ["cluster", "certs", "monitoring"]
      when: global_cluster_sizing != "small"
    - role: logcollect
      tags: ["cluster", "logcollect"]
      when: global_cluster_sizing == "large"
    - role: backup
      tags: ["cluster", "backup"]
      when: backup_s3_accesskey_secret != ""
    - role: bench
      tags: ["cluster", "bench"]

...
