---
- name: Install prerequisites and kubernetes packages
  hosts:
    - manager
    - nodes
  strategy: linear
  roles:
    - role: base
    - role: crio
    - role: kubernetes
      become: true

- name: Init kubernetes on manager node
  hosts:
    - manager
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cert
    - role: helm
    - role: k8s

- name: Init kubernetes on worker nodes
  hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s

- name: Postinstall fine-tuning and install tools & services
  hosts:
    - manager
  serial: 1
  strategy: linear
  run_once: true
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cni
    - role: postinstall
    - role: ingress
    - role: kubedashboard
    - role: opa

...
