---
- hosts:
    - master
    - nodes
  strategy: linear
  roles:
    - role: base
    - role: crio
    - role: kubernetes
      become: true

- hosts:
    - master
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cert
    - role: k8s

- hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s

- hosts:
    - master
  serial: 1
  strategy: linear
  run_once: yes
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s_postinstall
    - role: helm
    - role: ingress
    - role: istio
      when: global_istio_deploy == 1
    - role: keycloak
      when: global_keycloak_deploy == 1
    - role: gitea
      when: global_gitea_deploy == 1
    - role: jenkinsx
      when: global_jenkinsx_deploy == 1
    - role: sonar
      when: global_sonar_deploy == 1
    - role: kubedashboard
      when: global_dashboard_deploy == 1
#    - role: elk
#      when: global_elk_deploy == 1
#    - role: prometheus
#      when: global_monit_deploy == 1
#    - role: grafana
#      when: global_monit_deploy == 1

