---
- hosts:
    - master
    - nodes
  strategy: linear
  roles:
    - role: base
    - role: crio
    - role: kubernetes
      become: true

- hosts:
    - master
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: cert
    - role: k8s

- hosts:
    - nodes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s

- hosts:
    - master
  serial: 1
  strategy: linear
  run_once: yes
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s_postinstall
    - role: helm
    - role: ingress
    - role: kubedashboard
    - role: opa

