---

base_packages:
    - sshpass
    - git
    - chrony
    - debootstrap
    - vlan
    - python3
    - python3-dev
    - python3-pip
    - sudo
    - vim
    - htop
    - iotop
    - strace
    - rsync
    - links
    - ethtool
    - mailutils
    - acl
    - curl
    - wget
    - nmap
    - tcpdump
    - apt-transport-https
    - ca-certificates

...
