---

- name: Ensure .kube folder exist
  when: kubernetes_node_type == 'admin'
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Generate kubeconfig for current user
  become: true
  when: kubernetes_node_type == 'admin'
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    mode: '0600'

...
