---

- name: Ensure .kube folder exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'
#  run_once: true
#  delegate_to: "{{ k8s_man01_hostname }}"

- name: Generate kubeconfig for current user
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    mode: '0600'
#  run_once: true
#  delegate_to: "{{ k8s_man01_hostname }}"

...
