---

- name: Generate cloud-config file (for Openstack provider)
  become: true
  when: is_cloud == '1'
  ansible.builtin.template:
    src: templates/cloud.conf.j2
    dest: /etc/kubernetes/cloud-config
    mode: '0644'

- name: Generate kubeadm.conf for No Cloud provider
  become: true
  when: is_cloud == '0'
  ansible.builtin.template:
    src: templates/nocloud-kubeadm.conf.j2
    dest: /etc/kubernetes/kubeadm.conf
    mode: '0644'

- name: Generate kubeadm.conf for Openstack provider
  become: true
  when: is_cloud == '1'
  ansible.builtin.template:
    src: templates/cloud-kubeadm.conf.j2
    dest: /etc/kubernetes/kubeadm.conf
    mode: '0644'

- name: Get cloud ssl certificate file
  become: true
  when:
    - is_cloud == '1'
    - cloud_crt_path != ''
  ansible.builtin.copy:
    src: "{{ cloud_crt_path }}"
    dest: /usr/local/share/ca-certificates/cloud.crt
    mode: '0644'

- name: Add cloud cert to linux store
  become: true
  when:
    - is_cloud == '1'
    - cloud_crt_path != ''
  ansible.builtin.command: update-ca-certificates
  args:
    creates: "{{ ansible_env.HOME }}/.k8sinstall"

- name: Kubelet cloud arguments
  become: true
  when: is_cloud == '1'
  ansible.builtin.lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: "^Environment=\"KUBELET_KUBECONFIG_ARGS\".*$"
    line: >
      Environment="KUBELET_KUBECONFIG_ARGS=--cloud-provider=external
      --cloud-config=/etc/kubernetes/cloud-config
      --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
  notify: Restart kubelet service

- name: Init manager node
  become: true
  when:
    - kubernetes_node_type == 'admin'
  run_once: true
  ansible.builtin.shell: |
    kubeadm reset -f
    kubeadm init --config /etc/kubernetes/kubeadm.conf
  args:
    creates: "{{ ansible_env.HOME }}/.k8sinstall"

- name: Init kubeconfig for current user
  when: kubernetes_node_type == 'admin'
  run_once: true
  ansible.builtin.shell: >
    mkdir -p {{ ansible_env.HOME }}/.kube;
    sudo cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config;
    sudo chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config;
  args:
    creates: "{{ ansible_env.HOME }}/.k8sinstall"

- name: Get token from control-plane node
  become: true
  run_once: true
  when: kubernetes_node_type == 'admin'
  ansible.builtin.shell: |
    set -e -o pipefail
    kubeadm token list | tail -n +2 | head -n 1 | sed "s/ .*//"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.k8sinstall"
  register: k8s_token

- name: Add k8snode
  become: true
  when:
    - kubernetes_node_type == 'worker'
  ansible.builtin.command: >
    kubeadm join --token {{ hostvars[groups['master'][0]]['k8s_token'].stdout }} --discovery-token-unsafe-skip-ca-verification
    --node-name {{ inventory_hostname }} --cri-socket=unix:///var/run/crio/crio.sock {{ k8s_master_ip }}:443
  args:
    creates: "{{ ansible_env.HOME }}/.k8sinstall"

- name: Wait for kubernetes API is reachable
  ansible.builtin.wait_for:
    host: "{{ k8s_master_ip }}"
    port: 443
    delay: 5

- name: Ensure kubelet is in a running state
  become: true
  ansible.builtin.service:
    name: kubelet
    state: started
  register: k8s_kubelet_details
  until: k8s_kubelet_details.status.ActiveState == "active"
  retries: 25
  delay: 20

...
