---

- name: Create secret from cloud-config file for openstack controller manager
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloud-config
        namespace: kube-system
      type: Opaque
      data:
        cloud.conf: "{{ lookup('template', 'os-cloud.conf.j2') | b64encode }}"
  delegate_to: "{{ k8s_man01_hostname }}"

- name: Openstack controller manager
  run_once: true
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ k8s_os_provider_manifest_path }}/controller-manager/cloud-controller-manager-roles.yaml"
    - "{{ k8s_os_provider_manifest_path }}/controller-manager/cloud-controller-manager-role-bindings.yaml"
    - "{{ k8s_os_provider_manifest_path }}/controller-manager/openstack-cloud-controller-manager-ds.yaml"
  delegate_to: "{{ k8s_man01_hostname }}"

...
