---

- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes=={{ k8s_kubernetes_python_version }}
    break_system_packages: true

- name: Ensure /etc/kubernetes folder is present
  become: true
  ansible.builtin.file:
    path: /etc/kubernetes
    owner: root
    state: directory
    mode: '0755'

- name: Install route package
  become: true
  ansible.builtin.apt:
    name: net-tools
    state: present
    update_cache: true
    force: true

- name: Enable kernel module br-netfilter
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set br_netfilter parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

...
