---

- name: Create logcollect namespace
  kubernetes.core.k8s:
    name: "{{ logcollect_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add elastic chart repo
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: "{{ logcollect_elastic_repo }}"

- name: Deploy elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    chart_version: "{{ logcollect_elasticsearch_version }}"
    release_namespace: "{{ logcollect_namespace }}"
    values:
      esConfig:
        elasticsearch.yml: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: full
          xpack.security.authc:
            anonymous:
              username: anonymous
              roles: superuser
              authz_exception: true

- name: Wait for elasticsearch pods become ready
  ansible.builtin.command: "kubectl wait pod --all --namespace={{ logcollect_namespace }} --for=condition=Ready --timeout=900s"
  retries: 2
  delay: 10
  changed_when: false

- name: Deploy kibana
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    chart_version: "{{ logcollect_kibana_version }}"
    release_namespace: "{{ logcollect_namespace }}"
    values:
      ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
          - host: "{{ logcollect_kibana_domain }}"
            paths:
              - path: /
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/issuer: "{{ logcollect_cert_issuer }}"
          cert-manager.io/issuer-kind: ClusterIssuer
        tls:
          - secretName: logcollect-kibana-cert
            hosts:
              - "{{ logcollect_kibana_domain }}"

- name: Add fluentbit chart repo
  kubernetes.core.helm_repository:
    name: fluentbit
    repo_url: "{{ logcollect_fluentbit_repo }}"

- name: Deploy fluentbit
  kubernetes.core.helm:
    name: fluentbit
    chart_ref: fluentbit/fluent-bit
    chart_version: "{{ logcollect_fluentbit_version }}"
    release_namespace: "{{ logcollect_namespace }}"
    values:
      config:
        service: |
          [SERVICE]
              Flush         1
              Log_Level     info
              Daemon        off
              Parsers_File  parsers.conf
              HTTP_Server   On
              HTTP_Listen   0.0.0.0
              HTTP_Port     2020
        inputs: |
          [INPUT]
              Name              tail
              Tag               kube.*
              Path              /var/log/containers/*.log
              Parser            cri
              DB                /var/log/flb_kube.db
              Mem_Buf_Limit     5MB
              Skip_Long_Lines   On
          [INPUT]
              Name systemd
              Tag host.*
              Systemd_Filter _SYSTEMD_UNIT=kubelet.service
              Read_From_Tail On
        filters: |
          [FILTER]
              Name                kubernetes
              Match               kube.*
              Kube_URL            https://kubernetes.default.svc:443
              Merge_Log           On
              Keep_Log            Off
              K8S-Logging.Parser  On
              K8S-Logging.Exclude  On
        outputs: |
          [OUTPUT]
              Name            es
              Match           *
              Host            elasticsearch-master.{{ logcollect_namespace }}.svc
              Port            9200
              Suppress_Type_Name On
              Logstash_Format On
              Replace_Dots    On
              Retry_Limit     False
              tls On
              tls.verify Off
      customParsers: |
        [PARSER]
          Name cri
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
...
