---

- name: Add gatekeeper chart repo
  kubernetes.core.helm_repository:
    name: gatekeeper
    repo_url: "https://open-policy-agent.github.io/gatekeeper/charts"

- name: Create gatekeeper namespace
  kubernetes.core.k8s:
    name: "{{ opa_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Gatekeeper
  kubernetes.core.helm:
    name: gatekeeper
    chart_ref: gatekeeper/gatekeeper
    chart_version: "{{ opa_gatekeeper_version }}"
    release_namespace: "{{ opa_namespace }}"

- name: Create CRD opa templates
  kubernetes.core.k8s:
    state: present
    template: opa-templates.yml.j2

- name: Wait for ConstraintTemplate CRD to be available
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "constrainttemplates.templates.gatekeeper.sh"
  register: opa_crd_details
  until:
    - csi_crd_details.api_found is true
    - opa_crd_details.resources is defined
    - opa_crd_details.resources | length > 0
  retries: 10
  delay: 5

- name: Create CR opa rules
  kubernetes.core.k8s:
    state: present
    template: opa-rules.yml.j2
  retries: 3
  delay: 5

...
